### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [mfurkanndemir/gazelle#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by mfurkanndemir** [comment]
Hi, thanks for mentioning about missing license. I've created [COPYING](https://github.com/mfurkanndemir/gazelle/commit/79cd4f7788c3198e957935082df1ef976f73c312).
